server:
    port: 8081
spring:
    datasource:
        driverClassName: org.h2.Driver
        password: 'emp123'
        url: jdbc:h2:mem:employee_db
        username: sa
    h2:
        console:
            enabled: true
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        properties:
            hibernate:
                dialect: org.hibernate.dialect.H2Dialect
        show-sql: true
